name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Save Docker image
        run: |
          # Pass the secret as a build argument
          docker build --build-arg VITE_BASE_URL="${{ secrets.VITE_BASE_URL }}" -t my-front:${{ github.sha }} .
          docker save my-front:${{ github.sha }} | gzip > image.tar.gz

      - name: Copy image to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.IP_SERVER }}
          username: ${{ secrets.USER_SERVER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "image.tar.gz"
          target: "~/"

      - name: Execute remote commands via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.IP_SERVER }}
          username: ${{ secrets.USER_SERVER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            gunzip -c ~/image.tar.gz | docker load
            rm ~/image.tar.gz
            
            docker stop my-front || true
            docker rm my-front || true
            
            # Map Server Port 80 to Container Port 80
            docker run -d \
              --restart always \
              --name my-front \
              -p 80:80 \
              my-front:${{ github.sha }}
            
            docker image prune -a -f